import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";

const TodoDetail: NextPage = () => {
  const router = useRouter();
  const [text, setText] = useState<string>("");

  useEffect(() => {
    if (!router.isReady) {
      return;
    }
    setText(router.query.title as string);
  }, [router.isReady, router.query.title]);
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo詳細</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>ToDo詳細</h1>

        <div>
          <input
            type="text"
            placeholder="ToDo"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
        </div>
        <button
          onClick={() => {
            setText("");
          }}
        >
          削除
        </button>
        <button
          onClick={() => {
            setText("");
          }}
        >
          更新
        </button>

        <div>
          <Link href="/">
            <a href="./">一覧へ戻る</a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default TodoDetail;
